// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5A_xAI6a89kJYGdg7if1Ffw2sA0arDQ0',
    appId: '1:854984013848:web:1535ef51c6a8e32cda6b6d',
    messagingSenderId: '854984013848',
    projectId: 'educonnect-ec97a',
    authDomain: 'educonnect-ec97a.firebaseapp.com',
    storageBucket: 'educonnect-ec97a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtyZWS2607JwpBRswNK9kLlL1mG9sH20A',
    appId: '1:854984013848:android:3c15c084e5587d96da6b6d',
    messagingSenderId: '854984013848',
    projectId: 'educonnect-ec97a',
    storageBucket: 'educonnect-ec97a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2gnD4j0CiLdT7-8eNy8XHEDPxuyLmP-Y',
    appId: '1:854984013848:ios:e02ffa9bf6d416e8da6b6d',
    messagingSenderId: '854984013848',
    projectId: 'educonnect-ec97a',
    storageBucket: 'educonnect-ec97a.firebasestorage.app',
    iosBundleId: 'com.example.educonnectTeacherApp',
  );
}
